### ISSUE TITLE
crash on turned on "Strafe" and "Damage strafe" in speed

### ISSUE THREAD

**Issue by BotTele2** [suck/Opal#1]
в тг спамбан написать не могу кекс

**Comment by Razzy52** [comment]
bro, this is a rat r u retarded

**Comment by suck** [comment]
Hi, we will fix some crashes and rerelease soon. Sorry for the rushed release

**Comment by suck** [comment]
> bro, this is a rat r u retarded

Show proof or stfu this is for issues not baseless claims
